import { useCallback, useEffect, useMemo, useState } from "react";
import { Download, Edit, Plus, Search, Trash2, X } from "lucide-react";
import { toast } from "sonner";
import api, { assetUrl, formatApiError, formatINR } from "@/lib/api";

const today = () => new Intl.DateTimeFormat("en-CA", { timeZone: "Asia/Kolkata" }).format(new Date());
const EMPTY = { product_id: "", quantity: 1, selling_price_per_unit: "", buying_price_per_unit: "", platform_charges: 0, shipping_other_charges: 0, discount_adjustment: 0, selling_person_name: "", source: "Meesho", sale_date: today(), order_reference: "", notes: "" };
const card = "rounded-2xl border border-[var(--line)] bg-white p-5";
const field = "w-full rounded-xl border border-[var(--line)] bg-white px-3 py-2.5 text-sm outline-none focus:border-[var(--brand)]";
const sources = ["Website", "Meesho", "Referral"];
const sum = (a, b) => Number(a || 0) + Number(b || 0);

function Metric({ label, value, money = true }) {
  return <div className={card}><p className="text-xs text-[var(--ink-soft)]">{label}</p><p className="mt-2 text-xl font-semibold">{money ? formatINR(value) : Number(value || 0).toLocaleString("en-IN")}</p></div>;
}

export default function AdminSales() {
  const [rows, setRows] = useState([]);
  const [report, setReport] = useState(null);
  const [loading, setLoading] = useState(true);
  const [filters, setFilters] = useState({ start_date: "", end_date: "", source: "", product: "", category: "", selling_person: "", search: "" });
  const [products, setProducts] = useState([]);
  const [categories, setCategories] = useState([]);
  const [modal, setModal] = useState(false);
  const [editing, setEditing] = useState(null);
  const [form, setForm] = useState(EMPTY);
  const [productQuery, setProductQuery] = useState("");
  const [productResults, setProductResults] = useState([]);
  const [selectedProduct, setSelectedProduct] = useState(null);
  const [saving, setSaving] = useState(false);
  const [productSort, setProductSort] = useState("net_profit");

  const params = useMemo(() => Object.fromEntries(Object.entries(filters).filter(([, value]) => value)), [filters]);
  const load = useCallback(async () => {
    setLoading(true);
    try {
      const [list, summary] = await Promise.all([api.get("/admin/sales", { params }), api.get("/admin/sales/report", { params })]);
      setRows(list.data || []); setReport(summary.data);
    } catch (error) { toast.error(formatApiError(error.response?.data?.detail)); }
    finally { setLoading(false); }
  }, [params]);
  useEffect(() => { load(); }, [load]);
  useEffect(() => { api.get("/admin/products", { params: { limit: 500 } }).then(({ data }) => { const items = data.items || data; setProducts(items); setCategories([...new Set(items.map((p) => p.category_name || p.category).filter(Boolean))]); }).catch(() => {}); }, []);
  useEffect(() => {
    if (!modal || !productQuery.trim()) { setProductResults([]); return; }
    const timer = setTimeout(() => api.get("/admin/products", { params: { search: productQuery, limit: 20 } }).then(({ data }) => {
      const byText = data.items || data || [];
      const q = productQuery.trim().toLowerCase();
      const byCategory = products.filter((p) => `${p.category_name || ""} ${p.category || ""} ${p.group || ""}`.toLowerCase().includes(q));
      setProductResults([...new Map([...byText, ...byCategory].map((p) => [p.id, p])).values()].slice(0, 30));
    }).catch(() => setProductResults(products.filter((p) => `${p.category || ""} ${p.group || ""}`.toLowerCase().includes(productQuery.trim().toLowerCase())))), 200);
    return () => clearTimeout(timer);
  }, [productQuery, modal, products]);

  const chooseProduct = (p) => { setSelectedProduct(p); setProductQuery(p.name); setProductResults([]); setForm((f) => ({ ...f, product_id: p.id, selling_price_per_unit: p.selling_price ?? p.mrp ?? 0, buying_price_per_unit: p.buying_price ?? 0 })); };
  const openNew = () => { setEditing(null); setForm({ ...EMPTY, sale_date: today() }); setSelectedProduct(null); setProductQuery(""); setModal(true); };
  const openEdit = async (row) => {
    try {
      const { data: product } = await api.get(`/admin/products/${row.product_id}`);
      setSelectedProduct(product);
    } catch { setSelectedProduct({ id: row.product_id, name: row.product_name, images: row.product_image ? [row.product_image] : [], sku: row.sku, group: row.section, category: row.category }); }
    setEditing(row.sale_id); setForm({ ...EMPTY, ...row }); setProductQuery(row.product_name); setProductResults([]); setModal(true);
  };
  const save = async (event) => {
    event.preventDefault();
    setSaving(true);
    const payload = { ...form, quantity: Number(form.quantity), selling_price_per_unit: Number(form.selling_price_per_unit), buying_price_per_unit: Number(form.buying_price_per_unit), platform_charges: Number(form.platform_charges || 0), shipping_other_charges: Number(form.shipping_other_charges || 0), discount_adjustment: Number(form.discount_adjustment || 0) };
    try { if (editing) await api.put(`/admin/sales/${editing}`, payload); else await api.post("/admin/sales", payload); toast.success(editing ? "Sale updated" : "Sale recorded"); setModal(false); load(); }
    catch (error) { toast.error(formatApiError(error.response?.data?.detail)); }
    finally { setSaving(false); }
  };
  const remove = async (row) => { if (!window.confirm(`Delete the sale record for ${row.product_name}?`)) return; try { await api.delete(`/admin/sales/${row.sale_id}`); toast.success("Sale deleted"); load(); } catch (error) { toast.error(formatApiError(error.response?.data?.detail)); } };
  const exportCsv = async () => { try { const response = await api.get("/admin/sales/export", { params, responseType: "blob" }); const url = URL.createObjectURL(response.data); const a = document.createElement("a"); a.href = url; a.download = "sales-records.csv"; a.click(); URL.revokeObjectURL(url); } catch (error) { toast.error(formatApiError(error.response?.data?.detail)); } };

  const qty = Number(form.quantity || 0), selling = Number(form.selling_price_per_unit || 0), buying = Number(form.buying_price_per_unit || 0);
  const gross = selling * qty, cost = buying * qty, profit = gross - cost;
  const charges = sum(form.platform_charges, sum(form.shipping_other_charges, form.discount_adjustment));
  const net = profit - charges;
  const setFilter = (key, value) => setFilters((prev) => ({ ...prev, [key]: value }));

  return <div className="space-y-6">
    <header className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="font-serif text-3xl font-semibold">Sales Records</h1><p className="text-sm text-[var(--ink-soft)] mt-1">Manual sales and profitability, separate from Paid Website Orders.</p></div><div className="flex gap-2"><button type="button" onClick={exportCsv} className="inline-flex items-center gap-2 rounded-xl border border-[var(--line)] bg-white px-4 py-2.5 text-sm"><Download size={16}/> Export CSV</button><button type="button" onClick={openNew} className="inline-flex items-center gap-2 rounded-xl bg-[var(--ink)] px-4 py-2.5 text-sm text-white"><Plus size={17}/> Add Sale</button></div></header>
    <section><h2 className="mb-3 text-lg font-semibold">Overall Sales Report <span className="text-xs font-normal text-[var(--ink-soft)]">(current filters)</span></h2><div className="grid grid-cols-2 gap-3 lg:grid-cols-3">{[["Total Sales", report?.overall?.sales], ["Quantity Sold", report?.overall?.quantity, false], ["Total Buying Cost", report?.overall?.buying_cost], ["Gross Profit", report?.overall?.gross_profit], ["Platform / Other Charges", report?.overall?.charges], ["Net Profit", report?.overall?.net_profit]].map(([label, value, money]) => <Metric key={label} label={label} value={value} money={money !== false}/>)}</div></section>
    <section className="grid gap-4 xl:grid-cols-2"><div className={card}><h2 className="font-semibold mb-3">Source-wise Report</h2><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="text-xs text-[var(--ink-soft)]"><tr><th className="py-2">Source</th><th>Orders</th><th>Qty</th><th>Sales</th><th>Buying</th><th>Gross profit</th><th>Charges</th><th>Net profit</th></tr></thead><tbody>{sources.map((name) => { const r = report?.sources?.[name] || {}; return <tr key={name} className="border-t border-[var(--line)]"><td className="py-2 font-medium">{name}</td><td>{r.orders || 0}</td><td>{r.quantity || 0}</td><td>{formatINR(r.sales)}</td><td>{formatINR(r.buying_cost)}</td><td>{formatINR(r.gross_profit)}</td><td>{formatINR(r.charges)}</td><td>{formatINR(r.net_profit)}</td></tr>; })}</tbody></table></div></div>
    <div className={card}><div className="mb-3 flex items-center justify-between gap-2"><h2 className="font-semibold">Product-wise Profit</h2><select aria-label="Sort product report" className="rounded-lg border border-[var(--line)] px-2 py-1 text-xs" value={productSort} onChange={(e) => setProductSort(e.target.value)}><option value="sales">Highest sales</option><option value="net_profit">Highest profit</option><option value="quantity">Highest quantity</option><option value="lowest">Lowest profit</option></select></div>{[...(report?.products || [])].sort((a,b) => productSort === "lowest" ? a.net_profit-b.net_profit : b[productSort]-a[productSort]).slice(0,8).map((p) => <div key={p.product_id} className="flex justify-between border-t border-[var(--line)] py-2 text-sm"><span className="truncate pr-3">{p.product_name} <span className="text-[var(--ink-soft)]">· {p.quantity} sold · {formatINR(p.sales)} sales</span></span><span className="font-medium">{formatINR(p.net_profit)}</span></div>)}{!report?.products?.length && <p className="text-sm text-[var(--ink-soft)]">No sales recorded for these filters.</p>}</div>
    <div className={`${card} xl:col-span-2`}><h2 className="font-semibold mb-3">Source + Product Performance</h2>{report?.source_products?.length ? <div className="grid gap-4 md:grid-cols-3">{sources.map((source) => <div key={source}><h3 className="mb-2 text-sm font-semibold">{source}</h3>{report.source_products.filter((r) => r.source === source).map((r) => <div key={r.product_id} className="flex justify-between gap-2 border-t border-[var(--line)] py-2 text-xs"><span>{r.product_name} · {r.quantity} sold</span><b>{formatINR(r.net_profit)}</b></div>)}{!report.source_products.some((r) => r.source === source) && <p className="text-xs text-[var(--ink-soft)]">No recorded sales.</p>}</div>)}</div> : <p className="text-sm text-[var(--ink-soft)]">No source and product sales to report.</p>}</div></section>
    <section className={`${card} space-y-3`}><h2 className="font-semibold">Filter Sales</h2><div className="grid grid-cols-2 gap-2 md:grid-cols-4 xl:grid-cols-7"><label className="col-span-2 relative"><Search size={16} className="absolute left-3 top-3 text-[var(--ink-soft)]"/><input className={`${field} pl-9`} placeholder="Product, SKU, order or person" value={filters.search} onChange={(e) => setFilter("search", e.target.value)}/></label><input aria-label="From date" type="date" className={field} value={filters.start_date} onChange={(e) => setFilter("start_date", e.target.value)}/><input aria-label="To date" type="date" className={field} value={filters.end_date} onChange={(e) => setFilter("end_date", e.target.value)}/><select aria-label="Source filter" className={field} value={filters.source} onChange={(e) => setFilter("source", e.target.value)}><option value="">All sources</option>{sources.map((s) => <option key={s}>{s}</option>)}</select><select aria-label="Product filter" className={field} value={filters.product} onChange={(e) => setFilter("product", e.target.value)}><option value="">All products</option>{products.map((p) => <option key={p.id} value={p.id}>{p.name}</option>)}</select><select aria-label="Category filter" className={field} value={filters.category} onChange={(e) => setFilter("category", e.target.value)}><option value="">All categories</option>{categories.map((c) => <option key={c}>{c}</option>)}</select><input className={field} placeholder="Selling person" value={filters.selling_person} onChange={(e) => setFilter("selling_person", e.target.value)}/></div></section>
    <section className={card}><div className="mb-3 flex items-center justify-between"><h2 className="font-semibold">Manual Sales Records</h2><span className="text-xs text-[var(--ink-soft)]">{rows.length} records</span></div>{loading ? <p className="py-8 text-center text-sm text-[var(--ink-soft)]">Loading sales…</p> : <><div className="hidden overflow-x-auto md:block"><table className="w-full text-left text-sm"><thead className="text-xs text-[var(--ink-soft)]"><tr>{["Date", "Product", "Qty", "Source", "Selling person", "Selling", "Buying", "Gross profit", "Net profit", ""].map((x) => <th key={x} className="pb-3 pr-3">{x}</th>)}</tr></thead><tbody>{rows.map((r) => <tr key={r.sale_id} className="border-t border-[var(--line)]"><td className="py-3 pr-3 whitespace-nowrap">{r.sale_date}</td><td className="py-3 pr-3 min-w-40"><span className="font-medium">{r.product_name}</span><span className="block text-xs text-[var(--ink-soft)]">{r.sku}</span></td><td>{r.quantity}</td><td>{r.source}</td><td>{r.selling_person_name || "—"}</td><td>{formatINR(r.gross_selling_amount)}</td><td>{formatINR(r.total_buying_cost)}</td><td>{formatINR(r.gross_profit)}</td><td className="font-semibold">{formatINR(r.net_profit)}</td><td><div className="flex gap-1"><button title="Edit" onClick={() => openEdit(r)} className="rounded p-2 hover:bg-[var(--cream)]"><Edit size={15}/></button><button title="Delete" onClick={() => remove(r)} className="rounded p-2 text-red-600 hover:bg-red-50"><Trash2 size={15}/></button></div></td></tr>)}</tbody></table></div><div className="space-y-3 md:hidden">{rows.map((r) => <article key={r.sale_id} className="rounded-xl border border-[var(--line)] p-4"><div className="flex justify-between gap-2"><div><p className="font-medium">{r.product_name}</p><p className="text-xs text-[var(--ink-soft)]">{r.sale_date} · {r.source} · Qty {r.quantity}</p></div><div className="flex"><button aria-label="Edit sale" onClick={() => openEdit(r)} className="p-2"><Edit size={16}/></button><button aria-label="Delete sale" onClick={() => remove(r)} className="p-2 text-red-600"><Trash2 size={16}/></button></div></div><div className="mt-3 grid grid-cols-2 gap-1 text-xs"><span>Selling {formatINR(r.gross_selling_amount)}</span><span>Buying {formatINR(r.total_buying_cost)}</span><span>Gross profit {formatINR(r.gross_profit)}</span><span className="font-semibold">Net profit {formatINR(r.net_profit)}</span></div>{r.selling_person_name && <p className="mt-2 text-xs text-[var(--ink-soft)]">Sold by {r.selling_person_name}</p>}</article>)}{!rows.length && <p className="py-6 text-center text-sm text-[var(--ink-soft)]">No sales records found.</p>}</div></>}</section>

    {modal && <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-3" onMouseDown={(e) => { if (e.target === e.currentTarget) setModal(false); }}><form onSubmit={save} className="max-h-[94vh] w-full max-w-3xl overflow-y-auto rounded-2xl bg-[var(--cream)] p-5 shadow-2xl sm:p-7"><div className="mb-5 flex items-start justify-between"><div><h2 className="font-serif text-2xl font-semibold">{editing ? "Edit Sale" : "Add Sale"}</h2><p className="mt-1 text-xs text-[var(--ink-soft)]">Select an existing catalogue product. Product prices and details stay unchanged.</p></div><button type="button" onClick={() => setModal(false)} className="p-2"><X size={20}/></button></div>
      <label className="relative mb-4 block text-sm font-medium">Product *<input required autoComplete="off" className={`${field} mt-1`} placeholder="Search by product name or SKU" value={productQuery} onChange={(e) => { setProductQuery(e.target.value); if (form.product_id && e.target.value !== selectedProduct?.name) { setForm((f) => ({ ...f, product_id: "" })); setSelectedProduct(null); } }}/>{productResults.length > 0 && <div className="absolute z-10 mt-1 max-h-64 w-full overflow-y-auto rounded-xl border border-[var(--line)] bg-white shadow-xl">{productResults.map((p) => <button type="button" key={p.id} onClick={() => chooseProduct(p)} className="flex w-full items-center gap-3 p-3 text-left hover:bg-[var(--cream)]"><img src={assetUrl(p.images?.[0])} alt="" className="h-11 w-11 rounded-lg object-cover bg-[var(--cream)]"/><span><span className="block text-sm font-medium">{p.name}</span><span className="text-xs text-[var(--ink-soft)]">{p.sku || "No SKU"} · {p.category_name || p.category}</span></span></button>)}</div>}</label>
      {selectedProduct && <div className="mb-4 flex items-center gap-3 rounded-xl border border-[var(--line)] bg-white p-3"><img src={assetUrl(selectedProduct.images?.[0] || selectedProduct.product_image)} alt="" className="h-16 w-16 rounded-lg object-cover bg-[var(--cream)]"/><div><p className="font-semibold">{selectedProduct.name || selectedProduct.product_name}</p><p className="text-xs text-[var(--ink-soft)]">SKU: {selectedProduct.sku || "—"} · {(selectedProduct.group || selectedProduct.section || "").toString()} / {selectedProduct.category || ""}</p></div></div>}
      <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{[["quantity", "Quantity *", "number", { min: 1, step: 1 }], ["selling_price_per_unit", "Selling price per unit *", "number", { min: 0, step: "0.01" }], ["buying_price_per_unit", "Buying price per unit *", "number", { min: 0, step: "0.01" }], ["selling_person_name", "Selling person", "text"], ["source", "Source *", "select"], ["sale_date", "Sale date *", "date"], ["order_reference", "Order / sale reference", "text"], ["platform_charges", "Platform / transaction charges", "number", { min: 0, step: "0.01" }], ["shipping_other_charges", "Shipping / other charges", "number", { min: 0, step: "0.01" }], ["discount_adjustment", "Discount / adjustment", "number", { min: 0, step: "0.01" }]].map(([key, label, type, attrs]) => <label key={key} className="text-sm font-medium">{label}{type === "select" ? <select required className={`${field} mt-1`} value={form[key]} onChange={(e) => setForm((f) => ({ ...f, [key]: e.target.value }))}>{sources.map((s) => <option key={s}>{s}</option>)}</select> : <input required={label.includes("*")} type={type} className={`${field} mt-1`} value={form[key]} onChange={(e) => setForm((f) => ({ ...f, [key]: e.target.value }))} {...attrs}/>}</label>)}<label className="text-sm font-medium sm:col-span-2 lg:col-span-3">Notes<textarea className={`${field} mt-1`} rows={2} value={form.notes} onChange={(e) => setForm((f) => ({ ...f, notes: e.target.value }))}/></label></div>
      {form.source === "Website" && <p className="mt-3 rounded-lg bg-blue-50 p-3 text-xs text-blue-900">Manual Website entry. Website stock is handled by paid orders, so this record will not adjust inventory.</p>}
      {(form.source === "Meesho" || form.source === "Referral") && <p className="mt-3 rounded-lg bg-amber-50 p-3 text-xs text-amber-900">Saving this manual sale will reduce the selected product’s stock. Editing or deleting it will adjust stock accordingly.</p>}
      <div className="mt-4 rounded-xl bg-white p-4"><h3 className="mb-2 text-sm font-semibold">Profit Preview</h3><div className="grid grid-cols-2 gap-y-2 text-sm sm:grid-cols-5"><span>Gross sales<br/><b>{formatINR(gross)}</b></span><span>Buying cost<br/><b>{formatINR(cost)}</b></span><span>Gross profit<br/><b>{formatINR(profit)}</b></span><span>Charges + adjustment<br/><b>{formatINR(charges)}</b></span><span>Net profit<br/><b>{formatINR(net)}</b></span></div></div>
      <div className="mt-5 flex justify-end gap-2"><button type="button" onClick={() => setModal(false)} className="rounded-xl border border-[var(--line)] bg-white px-4 py-2.5 text-sm">Cancel</button><button disabled={saving || !form.product_id} className="rounded-xl bg-[var(--ink)] px-5 py-2.5 text-sm text-white disabled:opacity-50">{saving ? "Saving…" : "Save Sale"}</button></div>
    </form></div>}
  </div>;
}
